apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecko
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gecko
  template:
    metadata:
      labels:
        app: gecko
    spec:
      containers:
        - name: gecko
          image: facutk/gecko:0.0.13 # {"$imagepolicy": "flux-system:gecko"}
          volumeMounts:
            - name: volv
              mountPath: /data
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: local-path-pvc
