apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecko
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gecko
  template:
    metadata:
      labels:
        app: gecko
    spec:
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: local-path-pvc
      containers:
      - name: gecko
        image: facutk/gecko:0.0.21 # {"$imagepolicy": "flux-system:gecko"}
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        imagePullPolicy: Always
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 8080
