apiVersion: v1
kind: Service
metadata:
  name: simple-rest-golang-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: tcp
  selector:
    app: simple-rest-golang